export const LOGIN_BY_ADMIN_REQUEST = "LOGIN_BY_ADMIN_REQUEST";
export const LOGIN_BY_ADMIN_SUCCESS = "LOGIN_BY_ADMIN_SUCCESS";
export const LOGIN_BY_ADMIN_FAILED = "LOGIN_BY_ADMIN_FAILED";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const USER_STATUS_REQUEST = "USER_STATUS_REQUEST";
export const USER_STATUS_SUCCESS = "USER_STATUS_SUCCESS";
export const USER_STATUS_FAILED = "USER_STATUS_FAILED";

export const FETCH_ONE_USER_REQUEST = "FETCH_ONE_USER_REQUEST";
export const FETCH_ONE_USER_SUCCESS = "FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILED = "FETCH_ONE_USER_FAILED";

export const ADD_RESOURCE_REQUEST = "ADD_RESOURCE_REQUEST";
export const ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS";
export const ADD_RESOURCE_FAILED = "ADD_RESOURCE_FAILED";
