export const LOGIN_BY_ADMIN_REQUEST = "LOGIN_BY_ADMIN_REQUEST";
export const LOGIN_BY_ADMIN_SUCCESS = "LOGIN_BY_ADMIN_SUCCESS";
export const LOGIN_BY_ADMIN_FAILED = "LOGIN_BY_ADMIN_FAILED";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const USER_STATUS_REQUEST = "USER_STATUS_REQUEST";
export const USER_STATUS_SUCCESS = "USER_STATUS_SUCCESS";
export const USER_STATUS_FAILED = "USER_STATUS_FAILED";

export const FETCH_ONE_USER_REQUEST = "FETCH_ONE_USER_REQUEST";
export const FETCH_ONE_USER_SUCCESS = "FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILED = "FETCH_ONE_USER_FAILED";

export const ADD_RESOURCE_REQUEST = "ADD_RESOURCE_REQUEST";
export const ADD_RESOURCE_SUCCESS = "ADD_RESOURCE_SUCCESS";
export const ADD_RESOURCE_FAILED = "ADD_RESOURCE_FAILED";

export const ADD_EXPERT_REQUEST = "ADD_EXPERT_REQUEST";
export const ADD_EXPERT_SUCCESS = "ADD_EXPERT_SUCCESS";
export const ADD_EXPERT_FAILED = "ADD_EXPERT_FAILED";

export const FETCH_RESOURCES_REQUEST = "FETCH_RESOURCES_REQUEST";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";
export const FETCH_RESOURCES_FAILED = "FETCH_RESOURCES_FAILED";

export const FETCH_ONE_RESOURCE_REQUEST = "FETCH_ONE_RESOURCE_REQUEST";
export const FETCH_ONE_RESOURCE_SUCCESS = "FETCH_ONE_RESOURCE_SUCCESS";
export const FETCH_ONE_RESOURCE_FAILED = "FETCH_ONE_RESOURCE_FAILED";

export const FETCH_ONE_EXPERT_REQUEST = "FETCH_ONE_EXPERT_REQUEST";
export const FETCH_ONE_EXPERT_SUCCESS = "FETCH_ONE_EXPERT_SUCCESS";
export const FETCH_ONE_EXPERT_FAILED = "FETCH_ONE_EXPERT_FAILED";

export const ADD_IMAGE_REQUEST = "ADD_RESOURCE_IMAGE_REQUEST";
export const ADD_IMAGE_SUCCESS = "ADD_RESOURCE_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILED = "ADD_RESOURCE_IMAGE_FAILED";

export const SET_IMAGE = "SET_IMAGE";
export const SET_TOKEN = "SET_TOKEN";
export const SET_RESOURCE_DATA = "SET_RESOURCE_DATA";
export const DELETE_RESOURCE_REQUEST = "DELETE_RESOURCE_REQUEST";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILED = "DELETE_RESOURCE_FAILED";

export const EDIT_RESOURCE_REQUEST = "EDIT_RESOURCE_REQUEST";
export const EDIT_RESOURCE_SUCCESS = "EDIT_RESOURCE_SUCCESS";
export const EDIT_RESOURCE_FAILED = "EDIT_RESOURCE_FAILED";

export const FETCH_EXPERTS_REQUEST = "FETCH_EXPERTS_REQUEST";
export const FETCH_EXPERTS_SUCCESS = "FETCH_EXPERTS_SUCCESS";
export const FETCH_EXPERTS_FAILED = "FETCH_EXPERTS_FAILED";

export const DELETE_EXPERT_REQUEST = "DELETE_EXPERT_REQUEST";
export const DELETE_EXPERT_SUCCESS = "DELETE_EXPERT_SUCCESS";
export const DELETE_EXPERT_FAILED = "DELETE_EXPERT_FAILED";


export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";




export const EDIT_EXPERT_REQUEST = "EDIT_EXPERT_REQUEST";
export const EDIT_EXPERT_SUCCESS = "EDIT_EXPERT_SUCCESS";
export const EDIT_EXPERT_FAILED = "EDIT_EXPERT_FAILED";

export const FETCH_EXPERT_SERVICE_REQUEST = "FETCH_EXPERT_SERVICE_REQUEST";
export const FETCH_EXPERT_SERVICE_SUCCESS = "FETCH_EXPERT_SERVICE_SUCCESS";
export const FETCH_EXPERT_SERVICE_FAILED = "FETCH_EXPERT_SERVICE_FAILED";

export const FETCH_USER_EXPERT_REQUEST = "FETCH_USER_EXPERT_REQUEST";
export const FETCH_USER_EXPERT_SUCCESS = "FETCH_USER_EXPERT_SUCCESS";
export const FETCH_USER_EXPERT_FAILED = "FETCH_USER_EXPERT_FAILED";

export const FETCH_USER_RESOURCE_REQUEST = "FETCH_USER_RESOURCE_REQUEST";
export const FETCH_USER_RESOURCE_SUCCESS = "FETCH_USER_RESOURCE_SUCCESS";
export const FETCH_USER_RESOURCE_FAILED = "FETCH_USER_RESOURCE_FAILED";
