const resourcesData = [
  {
    id: 1,
    name: "Monika",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    id: 1,
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    id: 1,
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    id: 1,
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    id: 1,
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
  {
    name: "Isha",
    format: "5656",
    pricing: "fghhd",
    unique_selling_proposition: "fghfghfgh",
    pros_and_cons: "fhfgh",
    details: "hfghfgh",
  },
];

export default resourcesData;
