const usersData = [
  {
    id: 0,
    name: "John Doe",
    email: "a@a.com",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 1,
    name: "Samppa Nori",
    email: "a@a.com",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 2,
    name: "Estavan Lykos",
    email: "a@a.com",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    email: "a@a.com",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 4,
    name: "Derick Maximinus",
    email: "a@a.com",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
];

export default usersData;
