const usersData = [
  {
    id: 0,
    name: "John Doe",
    email: "a@a.com",
    status: "Verified",
    country: "Australia",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 1,
    name: "Samppa Nori",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 2,
    name: "Estavan Lykos",
    email: "a@a.com",
    status: "Not Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 4,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 5,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 6,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 7,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 8,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 9,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 10,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
  {
    id: 11,
    name: "Derick Maximinus",
    email: "a@a.com",
    status: "Not Verified",
    country: "India",
    gender: "Male",
    current_role: "abc",
    current_industry: "abc",
    fulltime_work_experience: "5",
    reason_for_career_change: "abc",
  },
];

export default usersData;
